export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  author: string;
  publishedAt: string;
  readTime: string;
  tags: string[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "cocoa-powder-moisture-control-milling-packing",
    title: "Cocoa Powder Moisture Control: From Cake Milling to Hygienic Packing",
    excerpt:
      "How cocoa processors can distinguish a hot milling-line trend from the packed-product condition, select a representative online measurement point, and validate it against an agreed moisture reference without assuming one universal limit.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-10-10",
    readTime: "10 min",
    tags: [
      "cocoa powder moisture control",
      "cocoa cake milling moisture measurement",
      "cocoa powder hygroscopicity",
      "cocoa powder packing moisture",
      "online NIR moisture analyzer",
      "food powder moisture calibration",
      "cocoa powder process control",
    ],
  },
  {
    slug: "ammonium-phosphate-granule-moisture-dryer-cooler",
    title: "Ammonium Phosphate Granule Moisture: Control from Rotary Dryer to Cooler",
    excerpt:
      "How MAP and DAP producers can separate granulator water load, dryer-endpoint control, and post-cooler handling condition—then validate an online moisture trend against a defined, representative reference method.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-10-08",
    readTime: "10 min",
    tags: [
      "ammonium phosphate granule moisture",
      "MAP DAP dryer moisture control",
      "fertilizer cooler discharge measurement",
      "granular fertilizer caking control",
      "online NIR moisture analyzer",
      "microwave bulk moisture measurement",
      "fertilizer granulation process control",
    ],
  },
  {
    slug: "kaolin-moisture-control-filter-cake-spray-drying",
    title: "Kaolin Moisture Control: From Filter Cake to Spray Dryer and Calciner Feed",
    excerpt:
      "How kaolin producers can separate removable process water from mineral mass loss, measure a representative stream after filtration or drying, and connect an online trend to a defined laboratory reference.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-10-07",
    readTime: "10 min",
    tags: [
      "kaolin moisture control",
      "kaolin filter cake moisture",
      "kaolin spray dryer measurement",
      "clay processing moisture analysis",
      "online NIR moisture analyzer",
      "microwave bulk moisture measurement",
      "kaolin calciner feed control",
    ],
  },
  {
    slug: "paddy-rice-drying-moisture-control-storage-milling",
    title: "Paddy Rice Drying Moisture: An Online Measurement Strategy for Storage and Milling",
    excerpt:
      "How rice processors can make dryer-endpoint variation visible, distinguish dryer discharge from storage condition, and connect an online trend to a representative approved grain-moisture reference.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-10-02",
    readTime: "10 min",
    tags: [
      "paddy rice drying moisture control",
      "rice dryer endpoint measurement",
      "paddy storage moisture monitoring",
      "rice milling moisture management",
      "online NIR grain moisture",
      "microwave bulk moisture measurement",
      "rice dryer energy management",
    ],
  },
  {
    slug: "ddgs-dryer-discharge-moisture-control-ethanol-coproducts",
    title: "DDGS Dryer-Discharge Moisture: A Measurement Strategy for Ethanol Co-Products",
    excerpt:
      "How ethanol plants can separate wet-cake variability, syrup-blending effects, dryer performance and post-cooler moisture pickup—then connect a continuous online trend to a defined DDGS laboratory reference.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-09-30",
    readTime: "10 min",
    tags: [
      "DDGS dryer discharge moisture control",
      "distillers dried grains with solubles moisture",
      "ethanol coproduct drying measurement",
      "DDGS storage and flowability",
      "online NIR moisture analyzer",
      "online microwave moisture measurement",
      "NFTA 2.2.2.5 DDGS moisture",
    ],
  },
  {
    slug: "sugar-beet-pulp-drying-moisture-control-pelletizing",
    title: "Sugar-Beet Pulp Drying Moisture: A Measurement Strategy Before Pelletizing",
    excerpt:
      "How beet-sugar plants can make the large water load after pulp pressing visible before the dryer, link an online trend to an accepted vacuum-oven reference, and distinguish dryer control from finished-pellet verification.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-09-28",
    readTime: "10 min",
    tags: [
      "sugar beet pulp drying moisture control",
      "beet pulp press moisture measurement",
      "beet pulp pelletizing moisture",
      "online microwave moisture measurement",
      "online NIR moisture analyzer",
      "sugar beet dryer energy management",
      "ICUMSA GS8-6 beet pulp moisture",
    ],
  },
  {
    slug: "cement-raw-mill-feed-moisture-control",
    title: "Cement Raw-Mill Feed Moisture: A Measurement Strategy Before Grinding",
    excerpt:
      "How cement plants can make wet raw-material variation visible before grinding, relate an online trend to a defined laboratory reference, and use it to support dry-feed and drying decisions without assuming a universal moisture limit.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-09-24",
    readTime: "10 min",
    tags: [
      "cement raw mill moisture control",
      "cement raw material drying",
      "limestone moisture measurement",
      "online microwave moisture measurement",
      "online NIR moisture analyzer",
      "cement raw meal consistency",
      "bulk solids moisture monitoring",
    ],
  },
  {
    slug: "alumina-hydrate-filter-cake-moisture-calciner-feed",
    title: "Alumina Hydrate Filter-Cake Moisture: An Online Measurement Strategy for Calciner Feed",
    excerpt:
      "How alumina refineries can separate free filter-cake water from chemically bound hydrate water, place a representative online measurement before calcination, and connect the trend to a traceable mass-balance and laboratory plan.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-09-20",
    readTime: "10 min",
    tags: [
      "alumina hydrate filter cake moisture",
      "alumina calciner feed measurement",
      "Bayer process moisture control",
      "aluminium trihydrate dewatering",
      "online microwave moisture measurement",
      "alumina calcination energy",
      "ISO 806 alumina moisture on ignition",
    ],
  },
  {
    slug: "rpet-flake-drying-moisture-control-before-extrusion",
    title: "rPET Flake Drying Before Extrusion: Where Online Moisture Measurement Helps",
    excerpt:
      "How rPET processors can use a continuous moisture trend to manage variable washed-flake feed and dryer performance—while keeping a traceable low-level reference test for final extrusion release.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-09-18",
    readTime: "10 min",
    tags: [
      "rPET flake moisture control",
      "PET drying before extrusion",
      "recycled PET residual moisture",
      "online moisture measurement for plastics",
      "PET hydrolysis prevention",
      "Karl Fischer PET moisture testing",
      "plastic recycling process control",
    ],
  },
  {
    slug: "coal-conveyor-moisture-control-microwave-measurement",
    title: "Coal Conveyor Moisture Control: Building a Representative Microwave Measurement",
    excerpt:
      "How coal-handling and preparation plants can link a live conveyor moisture trend to an agreed total-moisture reference, compensate for changing bed depth, and use the signal for earlier process decisions.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-09-16",
    readTime: "10 min",
    tags: [
      "coal conveyor moisture measurement",
      "online microwave coal moisture analyzer",
      "coal total moisture sampling",
      "coal preparation plant moisture control",
      "conveyor bed depth compensation",
      "ASTM D3302 coal moisture",
      "bulk solids moisture monitoring",
    ],
  },
  {
    slug: "milk-powder-moisture-control-spray-dryer-fluid-bed",
    title: "Milk Powder Moisture Control: From Spray Dryer to Fluid Bed and Packing",
    excerpt:
      "How dairy processors can distinguish tower-discharge moisture from the finished packed-powder result, use a representative online signal at the right process point, and maintain a traceable relationship with ISO reference testing.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-09-14",
    readTime: "10 min",
    tags: [
      "milk powder moisture control",
      "spray dryer outlet moisture",
      "fluid bed drying dairy powder",
      "online NIR moisture analyzer",
      "milk powder packaging moisture",
      "ISO 5537 dried milk moisture",
      "dairy powder process control",
    ],
  },
  {
    slug: "iron-ore-pelletizing-moisture-control-green-pellets",
    title: "Iron Ore Pelletizing Moisture Control: From Filter Cake to Stronger Green Pellets",
    excerpt:
      "How pellet plants can distinguish filter-cake moisture from green-pellet moisture, place online measurement where it supports a specific operating decision, and connect continuous trends to representative sampling without copying a universal setpoint.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-09-12",
    readTime: "10 min",
    tags: [
      "iron ore pelletizing moisture control",
      "green pellet moisture measurement",
      "magnetite filter cake moisture",
      "bentonite pelletizing binder",
      "online NIR moisture analyzer",
      "microwave bulk moisture measurement",
      "iron ore moisture sampling",
    ],
  },
  {
    slug: "spray-dried-detergent-powder-moisture-control-post-tower",
    title: "Spray-Dried Detergent Powder Moisture Control: Separate Tower Drying from Post-Tower Pickup",
    excerpt:
      "How detergent-powder producers can define a defensible water reference, locate online measurement after the spray tower or before packing, and use continuous trends to investigate flow and caking risk without treating one moisture value as a universal specification.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-09-10",
    readTime: "10 min",
    tags: [
      "spray-dried detergent powder moisture",
      "detergent tower outlet measurement",
      "detergent powder caking control",
      "detergent powder flowability",
      "online NIR moisture analyzer",
      "microwave bulk moisture measurement",
      "Karl Fischer detergent water content",
    ],
  },
  {
    slug: "pvc-resin-moisture-control-dryer-discharge-compounding",
    title: "PVC Resin Moisture Control: From Dryer Discharge to a Traceable Compounding Signal",
    excerpt:
      "How PVC producers and compounders can define volatile matter correctly, select a representative online measurement point after drying or before blending, and connect continuous data to laboratory verification without copying a generic moisture target.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-09-07",
    readTime: "10 min",
    tags: [
      "PVC resin moisture control",
      "vinyl chloride resin volatile matter",
      "PVC dryer discharge measurement",
      "PVC dry blend moisture monitoring",
      "online NIR moisture analyzer",
      "microwave bulk moisture measurement",
      "PVC compounding quality control",
    ],
  },
  {
    slug: "animal-feed-pellet-moisture-control-cooling-storage",
    title: "Animal Feed Pellet Moisture Control: Cooling, Storage, and a Better Online Measurement Point",
    excerpt:
      "How feed mills can distinguish conditioning moisture from finished-pellet moisture, select a representative post-cooler measurement point, and use continuous data to investigate cooling and storage risk without treating one moisture limit as universal.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-09-04",
    readTime: "9 min",
    tags: [
      "animal feed pellet moisture control",
      "feed pellet cooler moisture measurement",
      "post-pellet cooling and storage",
      "online NIR moisture analyzer",
      "microwave bulk moisture measurement",
      "feed mill moisture calibration",
      "pellet storage mold prevention",
    ],
  },
  {
    slug: "wood-pellet-moisture-control-dryer-bagging-storage",
    title: "Wood Pellet Moisture Control: From Dryer Discharge to Bagging and Storage",
    excerpt:
      "How pellet producers can define moisture on a wet basis, place online measurement where it represents the finished stream, and use continuous data to manage drying, cooling, and protected storage without assuming one target fits every grade or customer specification.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-08-31",
    readTime: "9 min",
    tags: [
      "wood pellet moisture control",
      "wood pellet dryer discharge measurement",
      "pellet storage humidity control",
      "online NIR moisture analyzer",
      "microwave bulk moisture measurement",
      "wood pellet quality testing",
      "biomass pellet drying",
    ],
  },
  {
    slug: "granular-urea-moisture-control-cooling-caking",
    title: "Granular Urea Moisture Control: Cooling, Hygroscopic Pickup, and Caking Risk",
    excerpt:
      "How fertilizer producers can distinguish process moisture from humidity pickup, select a representative online measurement point after cooling, and use continuous data to protect granule flowability without applying a universal moisture limit.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-08-29",
    readTime: "9 min",
    tags: [
      "granular urea moisture control",
      "urea fertilizer caking prevention",
      "urea cooler discharge measurement",
      "online NIR moisture analyzer",
      "microwave bulk moisture measurement",
      "fertilizer hygroscopicity",
      "urea storage flowability",
    ],
  },
  {
    slug: "glass-batch-silica-sand-moisture-control",
    title: "Glass-Batch Silica Sand Moisture Control: Weighing, Mixing, and Furnace Feed",
    excerpt:
      "How glass plants can define silica-sand moisture at the batch house, select a representative online measurement point, and use continuous data to protect dry-material dosing and batch consistency without applying a universal moisture target.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-08-24",
    readTime: "9 min",
    tags: [
      "glass batch silica sand moisture",
      "glassmaking sand moisture control",
      "glass batch house weighing",
      "online microwave moisture measurement",
      "silica sand dryer control",
      "bulk solids moisture monitoring",
      "ASTM C566 moisture testing",
    ],
  },
  {
    slug: "green-coffee-moisture-control-drying-storage",
    title: "Green Coffee Moisture Control: From Drying Endpoint to Storage-Ready Beans",
    excerpt:
      "How coffee processors can define a traceable green-bean moisture reference, use online measurement at a representative transfer point, and protect drying consistency without confusing a live process trend with the export test result.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-08-23",
    readTime: "9 min",
    tags: [
      "green coffee moisture control",
      "coffee bean drying endpoint",
      "green coffee storage moisture",
      "online NIR moisture analyzer",
      "bulk coffee moisture measurement",
      "ISO 6673 coffee moisture",
      "coffee dryer process control",
    ],
  },
  {
    slug: "soda-ash-moisture-control-post-dryer-caking",
    title: "Soda Ash Moisture Control: Detecting Post-Dryer Pickup Before Caking and Glass Batch",
    excerpt:
      "How soda-ash producers can distinguish dryer-outlet moisture from post-dryer humidity pickup, choose a representative online measurement point, and calibrate against a reference method that separates water from bicarbonate-related loss on heating.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-08-21",
    readTime: "9 min",
    tags: [
      "soda ash moisture control",
      "sodium carbonate caking prevention",
      "soda ash dryer outlet measurement",
      "online NIR moisture analyzer",
      "microwave bulk moisture measurement",
      "glass batch raw materials",
      "ASTM E359 soda ash analysis",
    ],
  },
  {
    slug: "wheat-tempering-moisture-control-roller-milling",
    title: "Wheat Tempering Moisture Control: Measuring the Control Variable Before Roller Milling",
    excerpt:
      "How flour mills can define tempered-wheat moisture, verify water addition and equilibration, and use representative online data to support consistent roller-mill performance without treating one target as universal.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-08-16",
    readTime: "9 min",
    tags: [
      "wheat tempering moisture control",
      "roller milling moisture measurement",
      "flour mill water addition",
      "online NIR grain moisture",
      "wheat moisture equilibration",
      "bulk solids moisture monitoring",
      "milling process control",
    ],
  },
  {
    slug: "glass-fiber-roving-drying-moisture-control",
    title: "Glass-Fiber Roving Drying: Moisture Control from Wet Package to Finished Strand",
    excerpt:
      "How glass-fiber producers can define a meaningful moisture reference, choose a representative online measurement point, and use continuous trends to manage drying without treating one residual-moisture value as universal.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-08-14",
    readTime: "9 min",
    tags: [
      "glass fiber roving drying",
      "glass fiber moisture control",
      "textile glass moisture measurement",
      "online NIR moisture analyzer",
      "microwave bulk moisture measurement",
      "glass fiber sizing cure",
      "industrial dryer control",
    ],
  },
  {
    slug: "precipitated-silica-moisture-rubber-compounding",
    title: "Precipitated Silica Moisture in Rubber Compounding: A Better Control Point for Silanization",
    excerpt:
      "How to define and trend precipitated-silica volatile content before rubber mixing, select a representative online measurement point, and use the signal to manage feed consistency without treating one moisture value as universal.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-08-12",
    readTime: "9 min",
    tags: [
      "precipitated silica moisture",
      "silica rubber compounding",
      "silanization process control",
      "rubber additive moisture measurement",
      "online NIR moisture analyzer",
      "microwave bulk moisture measurement",
      "silica dryer control",
    ],
  },
  {
    slug: "wood-chip-boiler-fuel-moisture-control-wet-basis",
    title: "Wood-Chip Boiler Fuel Moisture Control: Why Wet-Basis Measurement Matters",
    excerpt:
      "A practical guide to defining wood-chip moisture on the right basis, choosing a representative online measurement point, and using continuous data to protect boiler fuel consistency without treating one target as universal.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-08-10",
    readTime: "9 min",
    tags: [
      "wood chip moisture control",
      "biomass boiler fuel moisture",
      "wet basis moisture measurement",
      "online microwave moisture measurement",
      "wood chip drying control",
      "biomass fuel quality",
      "bulk solids moisture monitoring",
    ],
  },
  {
    slug: "gypsum-calcination-free-water-crystal-water-control",
    title: "Gypsum Calcination Moisture Control: Separating Free Water from Crystal Water",
    excerpt:
      "A technical guide to measuring gypsum through drying and calcination, defining a useful reference value, and using online trends without confusing surface moisture with water of crystallization.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-08-06",
    readTime: "9 min",
    tags: [
      "gypsum calcination moisture control",
      "gypsum free water measurement",
      "gypsum crystal water",
      "stucco quality control",
      "online NIR moisture analyzer",
      "microwave bulk moisture measurement",
      "gypsum wallboard process",
    ],
  },
  {
    slug: "ceramic-press-feed-moisture-silo-equalization",
    title: "Ceramic Press-Feed Moisture: Why Silo Equalization Matters After Spray Drying",
    excerpt:
      "A practical guide to controlling the moisture and distribution of spray-dried ceramic powder between dryer discharge and press feed, with calibration and installation considerations for online measurement.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-08-04",
    readTime: "8 min",
    tags: [
      "ceramic press feed moisture",
      "spray dried ceramic powder",
      "ceramic powder silo equalization",
      "online NIR moisture measurement",
      "microwave bulk moisture measurement",
      "porcelain stoneware processing",
      "green tile density control",
    ],
  },
  {
    slug: "viscose-staple-fiber-moisture-regain-control",
    title: "Viscose Staple Fiber Moisture Regain: From Dryer Outlet to Bale Control",
    excerpt:
      "Why viscose-fiber moisture must be managed as a dynamic process variable—and how a representative online measurement can support conditioning, bale consistency, and disciplined quality verification.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-08-02",
    readTime: "8 min",
    tags: [
      "viscose staple fiber moisture",
      "viscose moisture regain control",
      "online NIR moisture measurement",
      "textile fiber conditioning",
      "fiber dryer outlet control",
      "bale moisture consistency",
      "regenerated cellulose fiber",
    ],
  },
  {
    slug: "calcium-carbonate-moisture-control-polymer-compounding",
    title: "Calcium Carbonate Moisture Control for High-Filler Polymer Compounding",
    excerpt:
      "Why residual water in calcium-carbonate-filled compounds needs a defined control strategy—and how representative online measurement can support drying, storage, and extrusion decisions.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-07-31",
    readTime: "9 min",
    tags: [
      "calcium carbonate moisture control",
      "high filler polymer compounding",
      "PVC additive moisture measurement",
      "online NIR moisture analyzer",
      "microwave bulk moisture measurement",
      "calcium carbonate drying",
      "polymer extrusion quality",
    ],
  },
  {
    slug: "foundry-green-sand-moisture-control-compactability",
    title: "Foundry Green Sand Moisture Control: From Water Percentage to Compactability",
    excerpt:
      "Why green-sand moisture needs to be managed with clay activity, temperature, and compactability—and how an online trend can support faster, more disciplined muller control.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-07-29",
    readTime: "9 min",
    tags: [
      "foundry green sand moisture control",
      "molding sand compactability",
      "online NIR moisture measurement",
      "bentonite green sand",
      "foundry sand testing",
      "sand casting quality",
      "muller moisture control",
    ],
  },
  {
    slug: "dried-noodle-moisture-control-drying-curve",
    title: "Dried Noodle Moisture Control: Managing the Drying Curve and Final Moisture",
    excerpt:
      "How noodle manufacturers can use continuous moisture trends to protect drying uniformity, reduce cracking risk, and verify a product-specific final-moisture target before packaging.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-07-27",
    readTime: "9 min",
    tags: [
      "dried noodle moisture control",
      "noodle drying curve",
      "online NIR moisture measurement",
      "instant noodle moisture",
      "food drying process control",
      "noodle crack prevention",
      "final moisture verification",
    ],
  },
  {
    slug: "sinter-mix-moisture-control-granulation-permeability",
    title: "Sinter Mix Moisture Control: Stabilizing Granulation and Bed Permeability",
    excerpt:
      "Why sinter-water control must follow ore blend and particle size, and how an online bulk-moisture signal can support more stable granulation and bed permeability.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-07-23",
    readTime: "8 min",
    tags: [
      "sinter mix moisture control",
      "iron ore granulation",
      "sinter bed permeability",
      "online microwave moisture measurement",
      "ironmaking process control",
      "bulk solids moisture",
      "ore blend management",
    ],
  },
  {
    slug: "carbon-black-pellet-drying-moisture-control",
    title: "Carbon Black Pellet Drying: Moisture Control Without Sacrificing Pellet Quality",
    excerpt:
      "A practical guide to measuring residual moisture after carbon black pellet drying, selecting a suitable online method, and commissioning the signal for reliable process control.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-07-21",
    readTime: "8 min",
    tags: [
      "carbon black pellet drying",
      "carbon black moisture control",
      "online microwave moisture measurement",
      "rotary dryer control",
      "rubber carbon black",
      "bulk solids moisture",
      "ASTM D1509",
    ],
  },
  {
    slug: "wood-fiberboard-hot-press-moisture-control",
    title: "Wood Fiberboard Hot Pressing: A Practical Guide to Moisture Control",
    excerpt:
      "How continuous wood-fiber moisture measurement can help MDF and particleboard plants stabilize mat preparation, pressing, and final board quality.",
    content: "technical guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-07-20",
    readTime: "8 min",
    tags: [
      "wood fiberboard",
      "MDF moisture control",
      "particleboard pressing",
      "wood fiber moisture",
      "online NIR measurement",
      "hot press process",
      "bulk solids control",
    ],
  },
  {
    slug: "corn-starch-drying-moisture-control",
    title: "Corn Starch Drying Moisture Control with Online NIR Measurement",
    excerpt:
      "How online moisture data helps starch plants reduce manual sampling, stabilize drying, and improve final product consistency.",
    content: "case study",
    category: "Case Study",
    author: "Application Engineering Team",
    publishedAt: "2026-07-08",
    readTime: "6 min",
    tags: ["corn starch", "drying", "online NIR"],
  },
  {
    slug: "baking-soda-moisture-measurement-guide",
    title: "Why Baking Soda Producers Need Faster Moisture Measurement",
    excerpt:
      "A practical guide to replacing long lab cycles with inline moisture feedback in sodium bicarbonate production.",
    content: "application guide",
    category: "Application Guide",
    author: "Application Engineering Team",
    publishedAt: "2026-07-06",
    readTime: "5 min",
    tags: ["baking soda", "sodium bicarbonate", "moisture control"],
  },
  {
    slug: "nano-calcium-carbonate-drying-quality",
    title: "Moisture Control in Nano Calcium Carbonate Drying",
    excerpt:
      "How better residual-moisture control helps protect whiteness, flowability, and drying efficiency in calcium carbonate lines.",
    content: "case study",
    category: "Case Study",
    author: "Application Engineering Team",
    publishedAt: "2026-07-03",
    readTime: "6 min",
    tags: ["calcium carbonate", "drying", "powder quality"],
  },
  {
    slug: "ceramic-spray-drying-moisture-stability",
    title: "Ceramic Spray Drying: Why Moisture Stability Matters",
    excerpt:
      "A closer look at how online moisture measurement supports granule quality and more stable ceramic powder production.",
    content: "application guide",
    category: "Application Guide",
    author: "Process Solutions Team",
    publishedAt: "2026-06-29",
    readTime: "5 min",
    tags: ["ceramics", "spray drying", "granule moisture"],
  },
  {
    slug: "washed-sand-moisture-for-concrete-batching",
    title: "Washed Sand Moisture Control for More Accurate Concrete Batching",
    excerpt:
      "Why continuous sand-moisture data can help batching plants adjust water faster and keep concrete performance more stable.",
    content: "case study",
    category: "Case Study",
    author: "Process Solutions Team",
    publishedAt: "2026-06-26",
    readTime: "5 min",
    tags: ["washed sand", "concrete batching", "aggregates"],
  },
  {
    slug: "how-to-choose-nir-vs-microwave-moisture-measurement",
    title: "How to Choose Between NIR and Microwave Moisture Measurement",
    excerpt:
      "A simple selection guide based on installation method, material type, penetration depth, and process goals.",
    content: "technology",
    category: "Technology",
    author: "Technical Marketing Team",
    publishedAt: "2026-06-22",
    readTime: "7 min",
    tags: ["NIR", "microwave", "selection guide"],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getBlogSlugs(): string[] {
  return blogPosts.map((p) => p.slug);
}

export function getFeaturedPosts(count = 4): BlogPost[] {
  return blogPosts.slice(0, count);
}
